# Generated by Django 4.2.29 on 2026-03-07 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=150, verbose_name='Nama Lengkap')),
                ('no_telepon', models.CharField(blank=True, max_length=20, null=True, verbose_name='No Telepon')),
                ('alamat', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_blok', models.CharField(max_length=20, unique=True, verbose_name='Kode Blok')),
                ('tipe_rumah', models.CharField(max_length=50, verbose_name='Tipe Rumah')),
                ('harga_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Harga Total')),
                ('status', models.CharField(choices=[('Tersedia', 'Tersedia'), ('Booking', 'Booking'), ('Terjual', 'Terjual')], default='Tersedia', max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='unit_fotos/')),
            ],
        ),
        migrations.CreateModel(
            name='Cicilan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_cicilan', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Jumlah Cicilan')),
                ('tanggal_jatuh_tempo', models.DateField(verbose_name='Tanggal Jatuh Tempo')),
                ('bulan', models.IntegerField(help_text='Bulan jatuh tempo (Contoh: 8, 9, 10)', verbose_name='Bulan')),
                ('tahun', models.IntegerField(help_text='Tahun jatuh tempo (Contoh: 2024)', verbose_name='Tahun')),
                ('keterangan_cicilan', models.CharField(help_text='Contoh: C1, C7', max_length=50, verbose_name='Keterangan')),
                ('denda', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Denda')),
                ('rekening', models.CharField(blank=True, choices=[('BRI', 'BRI'), ('BCA', 'BCA'), ('Mandiri', 'Mandiri'), ('BNI', 'BNI'), ('Lainnya', 'Lainnya'), ('-', 'Belum Tersedia')], default='-', max_length=20)),
                ('status_bayar', models.CharField(choices=[('Lunas', 'Lunas'), ('Belum Lunas', 'Belum Lunas')], default='Belum Lunas', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cicilan', to='properties.customer')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cicilan', to='properties.unit')),
            ],
            options={
                'verbose_name_plural': 'Cicilan',
            },
        ),
    ]
