# Generated by Django 4.2.29 on 2026-03-11 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perumahan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_perumahan', models.CharField(max_length=150, unique=True, verbose_name='Nama Perumahan')),
                ('lokasi', models.TextField(blank=True, null=True, verbose_name='Lokasi / Alamat')),
            ],
        ),
        migrations.AddField(
            model_name='unit',
            name='perumahan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.perumahan'),
        ),
    ]
