# Generated by Django 4.2.29 on 2026-03-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_perumahan_unit_perumahan'),
    ]

    operations = [
        migrations.AddField(
            model_name='cicilan',
            name='denda_persen',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Denda (%/bulan)'),
        ),
        migrations.AddField(
            model_name='cicilan',
            name='jumlah_dibayar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Jumlah Dibayar Aktual'),
        ),
        migrations.AddField(
            model_name='cicilan',
            name='metode_bayar',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Transfer', 'Transfer')], max_length=10, null=True, verbose_name='Metode Bayar'),
        ),
        migrations.AddField(
            model_name='cicilan',
            name='status_sp',
            field=models.CharField(choices=[('-', '-'), ('SP1', 'SP1'), ('SP2', 'SP2')], default='-', max_length=5, verbose_name='Status SP'),
        ),
        migrations.AddField(
            model_name='cicilan',
            name='tanggal_batas_bayar',
            field=models.DateField(blank=True, null=True, verbose_name='Batas Tanggal Bayar'),
        ),
        migrations.AddField(
            model_name='customer',
            name='bunga_per_tahun',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Khusus KPR. Isi 0 jika bukan KPR.', max_digits=5, verbose_name='Bunga Per Tahun (%)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='dp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='DP (Down Payment)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='metode_pembelian',
            field=models.CharField(blank=True, choices=[('KPR', 'KPR'), ('Cash Bertahap', 'Cash Bertahap'), ('Cash Keras', 'Cash Keras')], max_length=20, null=True, verbose_name='Metode Pembelian'),
        ),
        migrations.AddField(
            model_name='customer',
            name='nama_kontak_darurat',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nama Kontak Darurat'),
        ),
        migrations.AddField(
            model_name='customer',
            name='nik',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='NIK'),
        ),
        migrations.AddField(
            model_name='customer',
            name='no_kontak_darurat',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='No. Kontak Darurat'),
        ),
        migrations.AddField(
            model_name='customer',
            name='saldo_kredit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo Kredit'),
        ),
        migrations.AddField(
            model_name='customer',
            name='utj',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='UTJ (Uang Tanda Jadi)'),
        ),
        migrations.AddField(
            model_name='unit',
            name='blok',
            field=models.CharField(default='A', help_text='Contoh: A, B, C', max_length=10, verbose_name='Kode Blok'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='luas_bangunan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Luas Bangunan (m²)'),
        ),
        migrations.AddField(
            model_name='unit',
            name='luas_tanah',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Luas Tanah (m²)'),
        ),
        migrations.AddField(
            model_name='unit',
            name='nomor_rumah',
            field=models.CharField(default='00', help_text='Contoh: 1, 2, 3', max_length=10, verbose_name='Nomor Rumah'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cicilan',
            name='denda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Denda'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='tipe_rumah',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Hook', 'Hook')], default='Standard', max_length=20, verbose_name='Tipe Rumah'),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('perumahan', 'blok', 'nomor_rumah')},
        ),
        migrations.RemoveField(
            model_name='unit',
            name='kode_blok',
        ),
    ]
