# Generated by Django 4.2.29 on 2026-03-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_cicilan_denda_persen_cicilan_jumlah_dibayar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_perusahaan', models.CharField(default='PT. Nama Perusahaan', max_length=200, verbose_name='Nama Perusahaan')),
                ('alamat_perusahaan', models.TextField(blank=True, null=True, verbose_name='Alamat Perusahaan')),
                ('rekening_1_bank', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bank Rekening 1')),
                ('rekening_1_nomor', models.CharField(blank=True, max_length=50, null=True, verbose_name='No. Rekening 1')),
                ('rekening_1_cabang', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cabang Rekening 1')),
                ('rekening_2_bank', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bank Rekening 2')),
                ('rekening_2_nomor', models.CharField(blank=True, max_length=50, null=True, verbose_name='No. Rekening 2')),
                ('rekening_2_cabang', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cabang Rekening 2')),
                ('catatan_surat', models.TextField(blank=True, help_text='Contoh: Free Smartlock, TV 43", Sertifikat, AJB, BPHTB', null=True, verbose_name='Catatan di Surat Pesanan')),
            ],
            options={
                'verbose_name': 'Informasi Perusahaan',
                'verbose_name_plural': 'Informasi Perusahaan',
            },
        ),
        migrations.RemoveField(
            model_name='customer',
            name='alamat',
        ),
        migrations.AddField(
            model_name='customer',
            name='alamat_kontak_darurat',
            field=models.TextField(blank=True, null=True, verbose_name='Alamat Kontak Darurat'),
        ),
        migrations.AddField(
            model_name='customer',
            name='alamat_ktp',
            field=models.TextField(blank=True, null=True, verbose_name='Alamat KTP'),
        ),
        migrations.AddField(
            model_name='customer',
            name='alamat_sekarang',
            field=models.TextField(blank=True, null=True, verbose_name='Alamat Sekarang'),
        ),
        migrations.AddField(
            model_name='customer',
            name='hubungan_kontak_darurat',
            field=models.CharField(blank=True, help_text='Contoh: Adik, Kakak, Orang Tua', max_length=50, null=True, verbose_name='Hubungan Kontak Darurat'),
        ),
        migrations.AddField(
            model_name='perumahan',
            name='desa_kelurahan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Desa/Kelurahan'),
        ),
        migrations.AddField(
            model_name='perumahan',
            name='kecamatan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kecamatan'),
        ),
    ]
